# -*- coding: utf-8 -*-
"""Hangman Games

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IsWE-8tbUzVd1ucsdKP79w76WmCI8sU
"""

import random

WORDS = ["python", "coding", "hangman", "laptop", "script"]

def display_state(guessed_letters, word, wrong_guesses):
    print("\n" + "="*40)

    stages = [
        """
           -----
           |   |
               |
               |
               |
               |
        =========""",
        """
           -----
           |   |
           O   |
               |
               |
               |
        =========""",
        """
           -----
           |   |
           O   |
           |   |
               |
               |
        =========""",
        """
           -----
           |   |
           O   |
          /|   |
               |
               |
        =========""",
        """
           -----
           |   |
           O   |
          /|\\  |
               |
               |
        =========""",
        """
           -----
           |   |
           O   |
          /|\\  |
          /    |
               |
        =========""",
        """
           -----
           |   |
           O   |
          /|\\  |
          / \\  |
               |
        ========="""
    ]

    print(stages[wrong_guesses])

    display_word = " ".join(
        letter if letter in guessed_letters else "_"
        for letter in word
    )
    print(f"\n  Word: {display_word}")
    print(f"  Wrong guesses left: {6 - wrong_guesses}")

    wrong_letters = [l for l in guessed_letters if l not in word]
    if wrong_letters:
        print(f"  Wrong letters: {', '.join(sorted(wrong_letters))}")
    print("="*40)

def hangman():
    word = random.choice(WORDS)
    guessed_letters = set()
    wrong_guesses = 0
    max_wrong = 6

    print("\nWelcome to Hangman!")
    print("Guess the word - you have 6 incorrect guesses before game over.\n")

    while wrong_guesses < max_wrong:
        display_state(guessed_letters, word, wrong_guesses)

        if all(letter in guessed_letters for letter in word):
            print(f"\nYou won! The word was: '{word}'")
            break

        guess = input("\n  Enter a letter: ").strip().lower()

        if not guess or not guess.isalpha() or len(guess) != 1:
            print("  Please enter a single letter.")
            continue

        if guess in guessed_letters:
            print(f"  You already guessed '{guess}'. Try another letter.")
            continue

        guessed_letters.add(guess)

        if guess in word:
            print(f"  '{guess}' is in the word!")
        else:
            wrong_guesses += 1
            print(f"  '{guess}' is NOT in the word.")

    else:
        display_state(guessed_letters, word, wrong_guesses)
        print(f"\nGame over! The word was: '{word}'")

    play_again = input("\nPlay again? (y/n): ").strip().lower()
    if play_again == 'y':
        hangman()
    else:
        print("\nThanks for playing! Goodbye.")

if __name__ == "__main__":
    hangman()