# -*- coding: utf-8 -*-
"""Stock Potfolio Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxsMRWBGh7YEW4iBdbZOI7CLhsEN-g20
"""

STOCK_PRICES = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 140,
    "MSFT": 380,
    "AMZN": 185,
    "NFLX": 620,
    "META": 510,
    "NVDA": 950
}

def display_available_stocks():
    print("\nAvailable Stocks:")
    print("-" * 35)
    print(f"{'Symbol':<10} {'Price (USD)':>12}")
    print("-" * 35)
    for symbol, price in STOCK_PRICES.items():
        print(f"{symbol:<10} ${price:>11,.2f}")
    print("-" * 35)

def get_portfolio():
    portfolio = {}
    print("\nEnter your stock holdings (type 'done' to finish):")

    while True:
        symbol = input("\n  Stock symbol (e.g., AAPL): ").strip().upper()

        if symbol == "DONE":
            break

        if symbol not in STOCK_PRICES:
            print(f"  '{symbol}' not found. Please choose from the available stocks above.")
            continue

        try:
            quantity = int(input(f"  Quantity of {symbol}: ").strip())
            if quantity <= 0:
                print("  Quantity must be a positive number.")
                continue
            portfolio[symbol] = portfolio.get(symbol, 0) + quantity
        except ValueError:
            print("  Invalid quantity. Please enter a whole number.")

    return portfolio

def calculate_investment(portfolio):
    results = []
    total = 0

    for symbol, quantity in portfolio.items():
        price = STOCK_PRICES[symbol]
        value = price * quantity
        total += value
        results.append((symbol, quantity, price, value))

    return results, total

def display_summary(results, total):
    print("\n" + "=" * 55)
    print("           PORTFOLIO SUMMARY")
    print("=" * 55)
    print(f"{'Stock':<8} {'Qty':>6} {'Price':>12} {'Value':>14}")
    print("-" * 55)

    for symbol, quantity, price, value in results:
        print(f"{symbol:<8} {quantity:>6} ${price:>11,.2f} ${value:>13,.2f}")

    print("-" * 55)
    print(f"{'TOTAL INVESTMENT VALUE':>41}  ${total:>13,.2f}")
    print("=" * 55)

def save_results(results, total):
    print("\nSave your portfolio summary?")
    print("  [1] Save as .txt")
    print("  [2] Save as .csv")
    print("  [3] Skip saving")

    choice = input("\n  Enter choice (1/2/3): ").strip()

    if choice == "1":
        filename = "portfolio_summary.txt"
        with open(filename, "w") as f:
            f.write("STOCK PORTFOLIO SUMMARY\n")
            f.write("=" * 45 + "\n")
            f.write(f"{'Stock':<8} {'Qty':>6} {'Price':>12} {'Value':>14}\n")
            f.write("-" * 45 + "\n")
            for symbol, quantity, price, value in results:
                f.write(f"{symbol:<8} {quantity:>6} ${price:>11,.2f} ${value:>13,.2f}\n")
            f.write("-" * 45 + "\n")
            f.write(f"TOTAL INVESTMENT: ${total:,.2f}\n")
        print(f"  Saved as '{filename}'")

    elif choice == "2":
        filename = "portfolio_summary.csv"
        with open(filename, "w") as f:
            f.write("Stock Symbol,Quantity,Price per Share (USD),Total Value (USD)\n")
            for symbol, quantity, price, value in results:
                f.write(f"{symbol},{quantity},{price:.2f},{value:.2f}\n")
            f.write(f"TOTAL,,,{total:.2f}\n")
        print(f"  Saved as '{filename}'")

    else:
        print("  Skipped saving.")

def main():
    print("=" * 55)
    print("       STOCK PORTFOLIO TRACKER")
    print("=" * 55)

    display_available_stocks()
    portfolio = get_portfolio()

    if not portfolio:
        print("\nNo stocks entered. Exiting.")
        return

    results, total = calculate_investment(portfolio)
    display_summary(results, total)
    save_results(results, total)

    print("\nThank you for using Stock Portfolio Tracker!\n")

if __name__ == "__main__":
    main()