# -*- coding: utf-8 -*-
"""Task Automation with Python Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lz7IKYMNMLAKNf8kzw0kq_ZX1oWScoN-
"""

# Create a sample emails.txt file

text = """
Hello John,

Please contact us at support@example.com.
You can also email admin123@gmail.com or hr@codealpha.tech.

For queries:
info@yahoo.com
student2026@college.edu.in

Thank you!
"""

with open("emails.txt", "w") as file:
    file.write(text)

print("emails.txt created successfully!")

import re

# Read the input file
with open("emails.txt", "r") as file:
    text = file.read()

# Regular expression to find email addresses
emails = re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", text)

# Save extracted emails to output.txt
with open("output.txt", "w") as file:
    for email in emails:
        file.write(email + "\n")

# Display extracted emails
print("Extracted Email Addresses:")
for email in emails:
    print(email)

print("\nSaved successfully to output.txt")

from google.colab import files

files.download("output.txt")